import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Safety & Trust — Nightingale",
  description: "Every Nightingale consultation is reviewed by an AHPRA-registered GP. Learn how our human-in-the-loop model keeps you safe.",
};

export default function SafetyPage() {
  return (
    <main className="pt-16 pb-20">
      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-6 mb-24">
        <div className="max-w-3xl">
          <span className="inline-block px-3 py-1 rounded-full bg-secondary-container text-on-secondary-container font-label-sm mb-6 uppercase tracking-wider">
            The Nightingale Standard
          </span>
          <h1 className="font-display-xl text-display-xl text-primary mb-6">
            Medical safety, <br />
            <span className="text-secondary">reimagined for digital care.</span>
          </h1>
          <p className="text-body-lg font-body-lg text-outline max-w-2xl">
            We combine the rigour of Australian healthcare regulations with the precision of Human-in-the-Loop AI to
            ensure every interaction is clinical-grade and secure.
          </p>
        </div>
      </section>

      {/* HITL Diagram */}
      <section className="max-w-7xl mx-auto px-6 mb-32">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-gutter">
          <div className="lg:col-span-12 mb-12">
            <h2 className="font-headline-lg text-headline-lg text-primary mb-4 text-center">
              Human-in-the-Loop Architecture
            </h2>
            <p className="text-body-md font-body-md text-outline text-center max-w-2xl mx-auto">
              AI never acts alone. Every clinical insight is generated by AI and verified by an Australian-registered
              General Practitioner before reaching you.
            </p>
          </div>

          {/* Diagram */}
          <div
            className="lg:col-span-12 p-12 rounded-3xl overflow-hidden relative border border-outline-variant"
            style={{
              background: "rgba(255, 255, 255, 0.7)",
              backdropFilter: "blur(12px)",
            }}
          >
            <div className="flex flex-col md:flex-row justify-between items-center relative z-10 gap-12">
              {[
                { icon: "person", label: "Patient", sub: "Input & Context", color: "bg-primary-fixed text-primary" },
                { icon: "neurology", label: "AI Diagnostic Engine", sub: "Clinical Synthesis", color: "bg-secondary text-on-secondary", large: true },
                { icon: "medical_services", label: "Registered GP", sub: "Medical Validation", color: "bg-tertiary-fixed text-tertiary" },
                { icon: "verified", label: "Outcome", sub: "Safe Care Plan", color: "bg-primary-fixed text-primary" },
              ].map(({ icon, label, sub, color, large }, index, arr) => (
                <div key={label} className="flex flex-col md:flex-row items-center gap-4">
                  <div className="flex flex-col items-center gap-4 group">
                    <div
                      className={`${large ? "w-24 h-24 rounded-2xl" : "w-20 h-20 rounded-full"} ${color} flex items-center justify-center shadow-sm border border-white/20 transition-transform group-hover:scale-110`}
                    >
                      <span className={`material-symbols-outlined ${large ? "text-4xl" : "text-3xl"}`}>{icon}</span>
                    </div>
                    <div className="text-center">
                      <p className="font-label-sm text-primary font-bold">{label}</p>
                      <p className="text-clinical-data font-clinical-data text-outline">{sub}</p>
                    </div>
                  </div>
                  {index < arr.length - 1 && (
                    <div className="hidden md:flex items-center w-12 justify-center text-outline">
                      <span className="material-symbols-outlined text-secondary">arrow_forward</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
            {/* Decorative radial gradient */}
            <div className="absolute inset-0 opacity-5 pointer-events-none">
              <div
                className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[120%] h-[120%]"
                style={{ background: "radial-gradient(circle, #13696a 0%, transparent 70%)" }}
              />
            </div>
          </div>
        </div>
      </section>

      {/* Doctor Credentialing */}
      <section className="max-w-7xl mx-auto px-6 mb-32">
        <div className="flex flex-col md:flex-row gap-gutter items-center">
          <div className="w-full md:w-1/2 space-y-6">
            <h2 className="font-headline-lg text-headline-lg text-primary">Every doctor is vetted.</h2>
            <p className="text-body-lg font-body-lg text-outline">
              We don&apos;t just hire doctors; we partner with the best clinical minds in Australia. Our rigorous
              onboarding process ensures that every GP on the Nightingale platform meets the highest national standards.
            </p>
            <ul className="space-y-4">
              {[
                { icon: "verified_user", title: "AHPRA Registered", body: "Mandatory active registration with the Australian Health Practitioner Regulation Agency." },
                { icon: "history_edu", title: "Ongoing Training", body: "Continuous medical education in telehealth and digital-first clinical practices." },
                { icon: "gavel", title: "Professional Indemnity", body: "Comprehensive insurance coverage for all telehealth services provided." },
              ].map(({ icon, title, body }) => (
                <li key={title} className="flex items-start gap-4">
                  <span className="material-symbols-outlined text-secondary">{icon}</span>
                  <div>
                    <p className="font-bold font-clinical-data text-primary">{title}</p>
                    <p className="text-clinical-data font-clinical-data text-outline">{body}</p>
                  </div>
                </li>
              ))}
            </ul>
          </div>

          <div className="w-full md:w-1/2">
            <div className="relative p-doctor-margin bg-surface-container rounded-3xl border border-outline-variant">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                alt="Australian doctor"
                className="rounded-2xl w-full h-[400px] object-cover grayscale hover:grayscale-0 transition-all duration-700"
                src="/safety-profile-photo.png"
              />
              <div className="absolute -bottom-6 -left-6 bg-white p-6 rounded-2xl shadow-lg border border-outline-variant max-w-[240px]">
                <div className="flex items-center gap-2 mb-2">
                  <span className="w-2 h-2 rounded-full bg-secondary" />
                  <span className="font-label-sm text-secondary">Verified Practitioner</span>
                </div>
                <p className="font-clinical-data text-primary">Dr. Jane Smith</p>
                <p className="text-clinical-data font-clinical-data text-outline">AHPRA #MED0001234567</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Data Security */}
      <section className="bg-primary text-on-primary py-24 mb-32">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-16">
            <div>
              <h2 className="font-headline-lg text-headline-lg text-on-primary mb-8">
                Military-grade <br />data sovereignty.
              </h2>
              <p className="text-body-lg font-body-lg text-on-primary-container mb-12">
                Your health data is your most private asset. We host all Nightingale data on local Australian servers,
                ensuring full compliance with the Australian Privacy Act and My Health Record standards.
              </p>
              <div className="grid grid-cols-2 gap-8">
                <div className="space-y-2">
                  <p className="text-display-xl font-display-xl text-secondary-fixed">AES-256</p>
                  <p className="font-label-sm text-on-primary-container">End-to-End Encryption</p>
                </div>
                <div className="space-y-2">
                  <p className="text-display-xl font-display-xl text-secondary-fixed">AWS AU</p>
                  <p className="font-label-sm text-on-primary-container">Sydney Data Residency</p>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-1 gap-gutter">
              <div className="p-8 rounded-2xl bg-primary-container border border-on-primary/10">
                <span className="material-symbols-outlined text-secondary-fixed-dim text-3xl mb-4 block">location_on</span>
                <h3 className="font-headline-md text-headline-md mb-2">Data Sovereignty</h3>
                <p className="text-body-md font-body-md text-on-primary-container">
                  All clinical data is stored in Sydney. Your information never leaves Australian shores.
                </p>
              </div>
              <div className="p-8 rounded-2xl bg-primary-container border border-on-primary/10">
                <span className="material-symbols-outlined text-secondary-fixed-dim text-3xl mb-4 block">lock_reset</span>
                <h3 className="font-headline-md text-headline-md mb-2">Zero-Trust Access</h3>
                <p className="text-body-md font-body-md text-on-primary-container">
                  Strict 2FA requirements and time-limited access keys for clinical staff during review periods.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Emergency Protocol */}
      <section className="max-w-7xl mx-auto px-6 mb-32">
        <div className="bg-error-container/20 rounded-3xl p-12 border border-error/10 relative overflow-hidden">
          <div className="flex flex-col md:flex-row items-center gap-12 relative z-10">
            <div className="w-full md:w-2/3">
              <div className="flex items-center gap-3 text-error mb-4">
                <span className="material-symbols-outlined">emergency_home</span>
                <span className="font-label-sm uppercase tracking-widest">Emergency Protocols</span>
              </div>
              <h2 className="font-headline-lg text-headline-lg text-primary mb-6">Built-in emergency redirection.</h2>
              <p className="text-body-lg font-body-lg text-outline mb-8">
                Nightingale is not for emergencies. If our AI or a GP detects clinical indicators of a high-risk event,
                our system automatically terminates the digital flow and provides immediate instructions to call 000 or
                visit an ED.
              </p>
              <div className="flex flex-wrap gap-4">
                <div className="bg-white px-4 py-3 rounded-xl border border-error/20 flex items-center gap-3">
                  <span className="w-3 h-3 rounded-full bg-error animate-pulse" />
                  <span className="font-clinical-data text-primary">Instant Clinical Escalation</span>
                </div>
                <div className="bg-white px-4 py-3 rounded-xl border border-error/20 flex items-center gap-3">
                  <span className="material-symbols-outlined text-error text-xl">call</span>
                  <span className="font-clinical-data text-primary">Direct 000 Integration</span>
                </div>
              </div>
            </div>

            <div className="w-full md:w-1/3 flex justify-center">
              <div className="w-48 h-48 rounded-full border-8 border-error/10 flex items-center justify-center">
                <div className="text-center">
                  <a href="tel:000" className="text-display-xl font-display-xl text-error block">000</a>
                  <p className="font-label-sm text-error">Dial Immediately</p>
                </div>
              </div>
            </div>
          </div>
          {/* Decorative pulse */}
          <div className="absolute -top-24 -right-24 w-64 h-64 bg-error/5 rounded-full blur-3xl" />
        </div>
      </section>

      {/* Final CTA */}
      <section className="max-w-7xl mx-auto px-6 text-center">
        <h2 className="font-display-xl text-display-xl text-primary mb-6">Safe, verified, Australian care.</h2>
        <p className="text-body-lg font-body-lg text-outline mb-10 max-w-xl mx-auto">
          Join patients who trust Nightingale for their primary care needs.
        </p>
        <div className="flex flex-col sm:flex-row justify-center gap-4">
          <Link
            href="/register"
            className="bg-primary text-on-primary px-8 py-4 rounded-full font-label-sm text-lg hover:shadow-lg transition-all"
          >
            Get Started with Nightingale
          </Link>
          <Link
            href="/how-it-works"
            className="bg-white text-primary border border-outline-variant px-8 py-4 rounded-full font-label-sm text-lg hover:bg-surface-container transition-all"
          >
            How It Works
          </Link>
        </div>
      </section>
    </main>
  );
}
