import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        primary: "#002045",
        "on-primary": "#ffffff",
        "primary-container": "#1a365d",
        "on-primary-container": "#86a0cd",
        "inverse-primary": "#adc7f7",
        secondary: "#13696a",
        "on-secondary": "#ffffff",
        "secondary-container": "#a2eded",
        "on-secondary-container": "#1a6d6e",
        tertiary: "#321b00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4f2e00",
        "on-tertiary-container": "#c6955e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#faf9fd",
        "on-background": "#1a1c1e",
        surface: "#faf9fd",
        "surface-dim": "#dad9dd",
        "surface-bright": "#faf9fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f7",
        "surface-container": "#efedf1",
        "surface-container-high": "#e9e7eb",
        "surface-container-highest": "#e3e2e6",
        "on-surface": "#1a1c1e",
        "on-surface-variant": "#43474e",
        "inverse-surface": "#2f3033",
        "inverse-on-surface": "#f1f0f4",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#adc7f7",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#2d476f",
        "secondary-fixed": "#a5eff0",
        "secondary-fixed-dim": "#89d3d4",
        "on-secondary-fixed": "#002020",
        "on-secondary-fixed-variant": "#004f50",
        "tertiary-fixed": "#ffddba",
        "tertiary-fixed-dim": "#f2bc82",
        "on-tertiary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#633f0f",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6" }],
        "body-md": ["16px", { lineHeight: "1.5" }],
        "clinical-data": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "700" }],
      },
      spacing: {
        unit: "8px",
        "patient-margin": "32px",
        "doctor-margin": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 4px 12px rgba(0,0,0,0.03)",
        modal: "0 8px 32px rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [],
};

export default config;
